/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiPropertiesRouteImport } from './routes/api.properties'
import { Route as ImmobiliIndexRouteImport } from './routes/immobili.index'
import { Route as ImmobiliSlugRouteImport } from './routes/immobili.$slug'
import { Route as ApiPropertiesSlugRouteImport } from './routes/api.properties.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPropertiesRoute = ApiPropertiesRouteImport.update({
  id: '/api/properties',
  path: '/api/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmobiliIndexRoute = ImmobiliIndexRouteImport.update({
  id: '/immobili/',
  path: '/immobili/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmobiliSlugRoute = ImmobiliSlugRouteImport.update({
  id: '/immobili/$slug',
  path: '/immobili/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesSlugRoute = ApiPropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPropertiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/mcp': typeof McpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/properties': typeof ApiPropertiesRouteWithChildren
  '/immobili/$slug': typeof ImmobiliSlugRoute
  '/immobili/': typeof ImmobiliIndexRoute
  '/api/properties/$slug': typeof ApiPropertiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/mcp': typeof McpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/properties': typeof ApiPropertiesRouteWithChildren
  '/immobili/$slug': typeof ImmobiliSlugRoute
  '/immobili': typeof ImmobiliIndexRoute
  '/api/properties/$slug': typeof ApiPropertiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/mcp': typeof McpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/properties': typeof ApiPropertiesRouteWithChildren
  '/immobili/$slug': typeof ImmobiliSlugRoute
  '/immobili/': typeof ImmobiliIndexRoute
  '/api/properties/$slug': typeof ApiPropertiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/mcp'
    | '/privacy-policy'
    | '/.well-known/oauth-protected-resource'
    | '/api/properties'
    | '/immobili/$slug'
    | '/immobili/'
    | '/api/properties/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/mcp'
    | '/privacy-policy'
    | '/.well-known/oauth-protected-resource'
    | '/api/properties'
    | '/immobili/$slug'
    | '/immobili'
    | '/api/properties/$slug'
  id:
    | '__root__'
    | '/'
    | '/cookie-policy'
    | '/mcp'
    | '/privacy-policy'
    | '/.well-known/oauth-protected-resource'
    | '/api/properties'
    | '/immobili/$slug'
    | '/immobili/'
    | '/api/properties/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  McpRoute: typeof McpRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiPropertiesRoute: typeof ApiPropertiesRouteWithChildren
  ImmobiliSlugRoute: typeof ImmobiliSlugRoute
  ImmobiliIndexRoute: typeof ImmobiliIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties': {
      id: '/api/properties'
      path: '/api/properties'
      fullPath: '/api/properties'
      preLoaderRoute: typeof ApiPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immobili/': {
      id: '/immobili/'
      path: '/immobili'
      fullPath: '/immobili/'
      preLoaderRoute: typeof ImmobiliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immobili/$slug': {
      id: '/immobili/$slug'
      path: '/immobili/$slug'
      fullPath: '/immobili/$slug'
      preLoaderRoute: typeof ImmobiliSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/$slug': {
      id: '/api/properties/$slug'
      path: '/$slug'
      fullPath: '/api/properties/$slug'
      preLoaderRoute: typeof ApiPropertiesSlugRouteImport
      parentRoute: typeof ApiPropertiesRoute
    }
  }
}

interface ApiPropertiesRouteChildren {
  ApiPropertiesSlugRoute: typeof ApiPropertiesSlugRoute
}

const ApiPropertiesRouteChildren: ApiPropertiesRouteChildren = {
  ApiPropertiesSlugRoute: ApiPropertiesSlugRoute,
}

const ApiPropertiesRouteWithChildren = ApiPropertiesRoute._addFileChildren(
  ApiPropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  McpRoute: McpRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiPropertiesRoute: ApiPropertiesRouteWithChildren,
  ImmobiliSlugRoute: ImmobiliSlugRoute,
  ImmobiliIndexRoute: ImmobiliIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
